CREATE TABLE BATTLEUSERS (
ID INTEGER NOT NULL CONSTRAINT BAT_US PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
ENABLED INTEGER

-- GAMES_PLAYED INTEGER,
-- GAMES_WON INTEGER
);

CREATE TABLE AUTHORITIES(
ID INTEGER NOT NULL,
AUTHORITY VARCHAR(50) NOT NULL,
USERS_ID INTEGER  REFERENCES BATTLEUSERS(ID)
);