CREATE TABLE BATTLEUSER (
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
LOGIN VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
GAMES_PLAYED INTEGER,
GAMES_WON INTEGER
);